name: Create Pull Request
on: push

jobs:
  createPR:
    runs-on: ubuntu-latest
    steps:
    - uses: vsoch/pull-request-action@master
      env: 
        BRANCH_PREFIX = "update/"
        PULL_REQUEST_BRANCH = "master"
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
